name: Build, Push and Deploy DS to DockerHub

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

  

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_API: api-gateway
  REPO_CLIENT: client-service
  REPO_ACCOUNT: account-service

jobs:

  build:
    name: Build and Push Images to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses : actions/checkout@v3
      
      
      # Installer Java (à compléter)
      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Se connecter à DockerHub (à compléter)
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # Build API Gateway (à compléter)
      # working-directory: ds-api-gateway
      # run: |

      - name: build adn push api gateway
        run: |
          cd ds-api-gateway
          mvn clean package -DskipTests
          docker build -t $DOCKERHUB_USERNAME/ds-api-gateway:latest .
          docker push $DOCKERHUB_USERNAME/ds-api-gateway:latest 

      # Build Client Service (à compléter)
      # working-directory: ds-client-service
      # run: |
      - name: build and push client service
        run: |
          cd ds-client-service
          mvn clean package -DskipTests
          docker build -t $DOCKERHUB_USERNAME/ds-client-service:latest .
          docker push $DOCKERHUB_USERNAME/ds-client-service:latest 

      # Build Account Service (à compléter)
      # working-directory: ds-account-service
      # run: |
      - name: build and push account service
        run: |
          cd ds-account-service
          mvn clean package -DskipTests
          docker build -t $DOCKERHUB_USERNAME/ds-account-service:latest .
          docker push $DOCKERHUB_USERNAME/ds-account-service:latest 

  deploy:
    name: Deploy All Services
    runs-on: ubuntu-latest
    # définir la dépendance avec le job build
    needs: build
    steps:
      - name: Simulate deployment
        run: |
          # Ajouter les messages nécessaires
